import Header from "@/components/Header";
import "./globals.css";
// import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Providers from "./Providers";

// reduc-toolkit
// import { store } from "@/stores";
// import { fetchBlogData } from "@/stores/user-store";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // await store.dispatch(fetchBlogData());

  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <Header />
          <Tabs /> */}
          {children}
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
