"use client"
import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

import axios from "axios";
import { useState } from "react";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState();

  var apikey = "d0c16c114ee5491397201a6ab5aa22ab";
  var type = "tesla";
  var date = "2022-12-17";
  var sortBy = "publishedAt";

  const url = `https://newsapi.org/v2/everything?q=${type}&form=${date}&sortBy=${sortBy}&apikey=${apikey}`;

  const GrabNews = () => {
    axios
      .get(url)
      .then((response) => {
        console.clear();
        setData(response.data);
        console.log(response.data);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  return (
    <>
        <h1>---------------------</h1>
      <h1>---------Axios------</h1>
      <h1>---------------------</h1>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={``}>
        <button onClick={() => GrabNews()}>Buraya tıkla</button>
        {data &&
          data.articles.map((d, index) => {
            return (
              <div key={index}>
                <div>{d.author} </div>
                <div>{d.title} </div>
                <div>{d.url} </div>
                <div>{d.urlToImage} </div>
                {/* <Image src={d.urlToImage} height={200} width={200} /> */}
              </div>
            );
          })}
      </main>
    </>
  );
}
